apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secret-provider
spec:
  provider: azure
  secretObjects:
  - data:
    - key: password
      objectName: db-password
    - key: user
      objectName: db-user
    secretName: db-secrets
    type: Opaque
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: <key-vault-name>       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    tenantId: <tenant-Id>                # The tenant ID of the key vault
    objects: |
      array:
        - |
          objectName: "db-password"
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: "db-user"
          objectType: secret
          objectVersion: ""

