apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secret-provider
spec:
  provider: vault
  secretObjects:
  - data:
    - key: password
      objectName: db-password
    - key: user
      objectName: db-user
    secretName: db-secrets
    type: Opaque
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "secrets-ro"
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/db-secrets"
        secretKey: "password"
      - objectName: "db-user"
        secretPath: "secret/data/db-secrets"
        secretKey: "user"

